# Houses of a given legislature (here: Northern Ireland Assembly, id:SO65GBkm),
# ordered by House name.
#
# To adapt: swap the id in the FILTER. To list every legislature's houses,
# delete the FILTER line.
PREFIX :   <https://id.parliament.uk/schema/>
PREFIX id: <https://id.parliament.uk/>

SELECT *
WHERE {
  ?Legislature a :Legislature ;
               :name ?LegislatureName ;
               :legislatureHasHouse ?House .
  ?House :name ?HouseName .

  FILTER ( ?Legislature IN ( id:SO65GBkm ) )
}
ORDER BY ?HouseName
