# fly.toml app configuration file generated for fpkg on 2026-05-01T15:26:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fpkg'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  HOST = '0.0.0.0'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/_health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
